### ISSUE TITLE
Shared CSS Properties

### ISSUE THREAD

**Issue by cyouh95** [Seb22/prj-rev-bwfs-dasmoto#3]
Try to find ways to select and style elements in a way that reduces repetition. For example, you could alternatively select all `h2` elements and specify these properties just once instead of 3 separate times:

```css
h2 {
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```

https://github.com/Seb22/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/css/style.css#L19-L38
